#pragma once

#include "quantum_keycodes.h"

// Custom Keycode Declarations
enum planck_keycodes {
  CKC_LAY_NUMBERS_R = SAFE_RANGE,
  CKC_LAY_MOVEMENT_F,
  CKC_LAY_FUNCTIONKEYS_V,
  CKC_LAY_LEFT_THUMB,
  CKC_LAY_RIGHT_THUMB,
  CKC_LAY_MOVEMENT_RIGHT_SCLN,


  CKC_EXCL,
  CKC_QUES,
  CKC_LSHIFT_EXCLAMATION_MARK,
  CKC_LSHIFT_QUESTION_MARK,


  // Oneshot modifiers
  CKC_ONESHOT_MODIFIER_LEFT_CTRL,
  CKC_ONESHOT_MODIFIER_RIGHT_CTRL,
  CKC_ONESHOT_MODIFIER_LEFT_ALT,
  CKC_ONESHOT_MODIFIER_RIGHT_ALT,
  CKC_ONESHOT_MODIFIER_LEFT_SHIFT,
  CKC_ONESHOT_MODIFIER_RIGHT_SHIFT,
  CKC_ONESHOT_MODIFIER_LEFT_GUI,
  CKC_ONESHOT_MODIFIER_RIGHT_GUI,

  // Shifted replacements
  CKC_REPLACE_SHIFTED_2,
  CKC_REPLACE_SHIFTED_3,
  CKC_REPLACE_SHIFTED_4,
  CKC_REPLACE_SHIFTED_5,
  CKC_REPLACE_SHIFTED_6,
  CKC_REPLACE_SHIFTED_9,
  CKC_REPLACE_SHIFTED_0,
};
