#pragma once

#include "quantum_keycodes.h"

// Custom Keycode Declarations
enum planck_keycodes {
  CKC_REMOVE_MODS = SAFE_RANGE,
  CKC_REMOVE_ONESHOTS,
  CKC_RESET_TAPPINGTERM,
  CKC_SET_TAPPINGTERM,
  CKC_LAY_MOUSE_Q,
  CKC_LAY_NUMBERS_R,
  CKC_LAY_MOVEMENT_F,
  CKC_EXCL,
  CKC_QUES,
  CKC_LAY_RIGHT_THUMB,

  CKC_ONESHOT_MODIFIER_LEFT_CTRL,
  CKC_ONESHOT_MODIFIER_RIGHT_CTRL,
  CKC_ONESHOT_MODIFIER_LEFT_ALT,
  CKC_ONESHOT_MODIFIER_RIGHT_ALT,
  CKC_ONESHOT_MODIFIER_LEFT_SHIFT,
  CKC_ONESHOT_MODIFIER_RIGHT_SHIFT,
  CKC_ONESHOT_MODIFIER_LEFT_GUI,
  CKC_ONESHOT_MODIFIER_RIGHT_GUI,

  CKC_REPLACE_SHIFTED_2,
  CKC_REPLACE_SHIFTED_3,
  CKC_REPLACE_SHIFTED_4,
  CKC_REPLACE_SHIFTED_5,
  CKC_REPLACE_SHIFTED_6,
  CKC_REPLACE_SHIFTED_9,
  CKC_REPLACE_SHIFTED_0,
};
