#pragma once

#include "modules/soycabanillas/src/monkeyboard_keycodes.h"

typedef enum  {
  _LQWERTY,
  _LLEFT_THUMB,
  _LRIGHT_THUMB,
  _LMOVEMENT,
  _LNUMBERS,
  _LFUNCTIONKEYS,
  _LMOVEMENT_RIGHT_PINK,
} custom_layers;

// Custom Keycode Declarations
typedef enum {
  CKC_LAY_NUMBERS_R = CUSTOM_KEYCODE_MIN,
  CKC_LAY_MOVEMENT_F,
  CKC_LAY_FUNCTIONKEYS_V,
  CKC_LAY_LEFT_THUMB,
  CKC_LAY_RIGHT_THUMB,
  CKC_LAY_MOVEMENT_RIGHT_SCLN,


  CKC_EXCL,
  CKC_QUES,

  // Oneshot modifiers
  CKC_ONESHOT_MODIFIER_LEFT_CTRL,
  CKC_ONESHOT_MODIFIER_RIGHT_CTRL,
  CKC_ONESHOT_MODIFIER_LEFT_ALT,
  CKC_ONESHOT_MODIFIER_RIGHT_ALT,
  CKC_ONESHOT_MODIFIER_LEFT_SHIFT,
  CKC_ONESHOT_MODIFIER_RIGHT_SHIFT,
  CKC_ONESHOT_MODIFIER_LEFT_GUI,
  CKC_ONESHOT_MODIFIER_RIGHT_GUI,

//   // Shifted replacements
//   CKC_REPLACE_SHIFTED_2,
//   CKC_REPLACE_SHIFTED_3,
//   CKC_REPLACE_SHIFTED_4,
//   CKC_REPLACE_SHIFTED_5,
//   CKC_REPLACE_SHIFTED_6,
//   CKC_REPLACE_SHIFTED_9,
//   CKC_REPLACE_SHIFTED_0,
} custom_keycodes;
